apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: goldengate
    app.kubernetes.io/managed-by: argocd
    goldengate.adcb/environment: {{ .Values.global.environment | quote }}
    goldengate.adcb/deployment-id: {{ .Values.global.deploymentId | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: PruneLast=true
