{{- if and .Values.source.enabled .Values.source.serviceAccount.create }}
{{- $annotations := dict }}
{{- if and .Values.source.csi.enabled .Values.source.csi.serviceAccountRoleArn }}
{{- $_ := set $annotations "eks.amazonaws.com/role-arn" .Values.source.csi.serviceAccountRoleArn }}
{{- end }}
{{- with .Values.source.serviceAccount.annotations }}
{{- range $key, $value := . }}
{{- $_ := set $annotations $key $value }}
{{- end }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goldengate.sourceServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "goldengate.labels" . | nindent 4 }}
    app.kubernetes.io/component: source
    app.kubernetes.io/engine: {{ .Values.source.engine | quote }}
{{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
{{- end }}
{{- end }}