{{- if and .Values.target.enabled .Values.target.csi.enabled }}
{{- if .Values.target.csi.admin.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ required "target.csi.admin.providerClassName is required when target.csi.admin.enabled=true" .Values.target.csi.admin.providerClassName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "goldengate.labels" . | nindent 4 }}
    app.kubernetes.io/component: target
    app.kubernetes.io/engine: {{ .Values.target.engine | quote }}
spec:
  provider: aws
  secretObjects:
    - secretName: {{ required "target.csi.admin.secretName is required when target.csi.admin.enabled=true" .Values.target.csi.admin.secretName }}
      type: Opaque
      data:
        - objectName: OGG_ADMIN
          key: {{ .Values.target.admin.usernameKey | default "OGG_ADMIN" }}
        - objectName: OGG_ADMIN_PWD
          key: {{ .Values.target.admin.passwordKey | default "OGG_ADMIN_PWD" }}
  parameters:
    region: {{ .Values.target.csi.region | quote }}
    objects: |
      - objectName: "{{ required "target.csi.admin.objectName is required when target.csi.admin.enabled=true" .Values.target.csi.admin.objectName }}"
        objectType: "{{ .Values.target.csi.admin.objectType | default "secretsmanager" }}"
        jmesPath:
{{- range .Values.target.csi.admin.jmesPath }}
          - path: "{{ .path }}"
            objectAlias: "{{ .objectAlias }}"
{{- end }}
---
{{- end }}
{{- if .Values.target.csi.certificate.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ required "target.csi.certificate.providerClassName is required when target.csi.certificate.enabled=true" .Values.target.csi.certificate.providerClassName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "goldengate.labels" . | nindent 4 }}
    app.kubernetes.io/component: target
    app.kubernetes.io/engine: {{ .Values.target.engine | quote }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.target.csi.region | quote }}
    objects: |
      - objectName: "{{ required "target.csi.certificate.objectName is required when target.csi.certificate.enabled=true" .Values.target.csi.certificate.objectName }}"
        objectType: "{{ .Values.target.csi.certificate.objectType | default "secretsmanager" }}"
        jmesPath:
{{- range .Values.target.csi.certificate.jmesPath }}
          - path: "{{ .path }}"
            objectAlias: "{{ .objectAlias }}"
{{- end }}
{{- end }}
{{- end }}
