{{- if and .Values.target.enabled .Values.target.serviceAccount.create }}
{{- $annotations := dict }}
{{- if and .Values.target.csi.enabled .Values.target.csi.serviceAccountRoleArn }}
{{- $_ := set $annotations "eks.amazonaws.com/role-arn" .Values.target.csi.serviceAccountRoleArn }}
{{- end }}
{{- with .Values.target.serviceAccount.annotations }}
{{- range $key, $value := . }}
{{- $_ := set $annotations $key $value }}
{{- end }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goldengate.targetServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "goldengate.labels" . | nindent 4 }}
    app.kubernetes.io/component: target
    app.kubernetes.io/engine: {{ .Values.target.engine | quote }}
{{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
{{- end }}
{{- end }}
