"""config.py: loads the staged goldengate-deployments.yaml registry (generated by hack/goldengate-deployment-model.py, mounted read-only into the pod) and derives runtime config."""
from __future__ import annotations

import os
import re
import time

import yaml

REPO_ROOT_ENV = "REPO_CONFIG_ROOT"
DEFAULT_REPO_ROOT = "/etc/gg-canonical"
DEPLOYMENTS_FILE_RELPATH = "goldengate-deployments.yaml"

DEFAULT_ADMIN_PORT = 8443
DEFAULT_METRICS_PORT = 9015

MAX_DEPLOYMENT_TYPE_LENGTH = 32
_DEPLOYMENT_TYPE_RE = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*\Z")

# Mirrors hack/goldengate-deployment-model.py's own _INGRESS_HOST_RE / hack/goldengate-environment.py's own _DNS_DOMAIN_RE -- re-validates the registry's already-canonically-resolved ingressHost here, defensively, rather than trusting it blindly (see _is_valid_ingress_host below); never re-derives it from name+dnsDomain (that rule now lives solely in hack/goldengate-deployment-model.py).
_DNS_DOMAIN_RE = re.compile(r"^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}\Z")


def is_safe_deployment_type(value):
    """Generic safe-token check, never a fixed engine allowlist; oracle/postgresql/sqlserver/mysql/distributed and future types are all accepted equally."""
    if not isinstance(value, str) or not value or len(value) > MAX_DEPLOYMENT_TYPE_LENGTH:
        return False
    return bool(_DEPLOYMENT_TYPE_RE.match(value))


def _is_literal_bool(value):
    """True only for the literal Python bool type -- mirrors hack/goldengate-deployment-model.py's own _is_literal_bool; YAML 1.1 "yes"/"no"/"true"/"false" strings and 0/1 integers must never pass (bool is a subclass of int in Python, but isinstance(1, bool) is still False -- only True/False themselves satisfy this)."""
    return isinstance(value, bool)


def _is_valid_ingress_host(value):
    """Structural re-validation of the registry's already-canonical ingressHost -- never a second hostname-derivation rule, only a shape check on the value hack/goldengate-deployment-model.py already resolved."""
    return isinstance(value, str) and bool(_DNS_DOMAIN_RE.match(value))

DEFAULTS = {
    "PORT": "8080",
    "STALE_AFTER_SECONDS": "120",
    "REFRESH_SECONDS": "30",
    "MONITOR_VERSION": "development",
}


class ConfigError(Exception):
    """Raised for missing/invalid process or deployment configuration."""


def _repo_root():
    return os.environ.get(REPO_ROOT_ENV, DEFAULT_REPO_ROOT)


def _get_int(env, name, default):
    raw = env.get(name, default)
    try:
        return int(raw)
    except (TypeError, ValueError):
        raise ConfigError(f"{name} must be an integer, got {raw!r}") from None


class MonitorConfig:
    def __init__(self, aws_region, dynamodb_table, port, stale_after_seconds,
                refresh_seconds, monitor_version, repo_config_root):
        self.aws_region = aws_region
        self.dynamodb_table = dynamodb_table
        self.port = port
        self.stale_after_seconds = stale_after_seconds
        self.refresh_seconds = refresh_seconds
        self.monitor_version = monitor_version
        self.repo_config_root = repo_config_root


def load_config(env) -> MonitorConfig:
    missing = sorted(name for name in ("AWS_REGION", "DYNAMODB_TABLE") if not env.get(name))
    if missing:
        raise ConfigError("Missing required environment variables: " + ", ".join(missing))

    port = _get_int(env, "PORT", DEFAULTS["PORT"])
    if not (1 <= port <= 65535):
        raise ConfigError(f"PORT must be between 1 and 65535, got {port}")

    stale_after_seconds = _get_int(env, "STALE_AFTER_SECONDS", DEFAULTS["STALE_AFTER_SECONDS"])
    if stale_after_seconds <= 0:
        raise ConfigError(f"STALE_AFTER_SECONDS must be a positive integer, got {stale_after_seconds}")

    refresh_seconds = _get_int(env, "REFRESH_SECONDS", DEFAULTS["REFRESH_SECONDS"])
    if refresh_seconds <= 0:
        raise ConfigError(f"REFRESH_SECONDS must be a positive integer, got {refresh_seconds}")

    return MonitorConfig(
        aws_region=env["AWS_REGION"],
        dynamodb_table=env["DYNAMODB_TABLE"],
        port=port,
        stale_after_seconds=stale_after_seconds,
        refresh_seconds=refresh_seconds,
        monitor_version=env.get("MONITOR_VERSION", DEFAULTS["MONITOR_VERSION"]),
        repo_config_root=env.get("REPO_CONFIG_ROOT", DEFAULT_REPO_ROOT),
    )


def _admin_host(name, runtime_namespace):
    return f"{name}.{runtime_namespace}.svc.cluster.local"


def _tls_server_name(name, dns_domain):
    return f"{name}.{dns_domain}"


def _console_url(ingress_host):
    """The runtime's own canonical GoldenGate UI URL: https://<ingressHost>/ -- ingress_host is ALWAYS the registry's already-canonically-resolved ingressHost (hack/goldengate-deployment-model.py's runtimeIngressHost: an explicit ingress.host override, or the "<deploymentId>.<dnsDomain>" default), never independently reconstructed here. Callers must validate ingress_host with _is_valid_ingress_host before calling this -- this function performs no validation of its own."""
    return f"https://{ingress_host}/"


def credential_paths(name, mount_root="/mnt/secrets-store"):
    """CSI-mounted credential file paths, derived from the canonical deployment name."""
    return f"{mount_root}/{name}-admin-user", f"{mount_root}/{name}-admin-password"


def load_deployments_document(repo_root=None):
    repo_root = repo_root or _repo_root()
    path = os.path.join(repo_root, DEPLOYMENTS_FILE_RELPATH)
    try:
        with open(path) as f:
            doc = yaml.safe_load(f)
    except OSError as e:
        raise ConfigError(f"could not read {path}: {e}") from e
    if not isinstance(doc, dict):
        raise ConfigError(f"{path}: document must be a mapping")
    return doc


def load_deployments(repo_root=None):
    """Returns the deployments document with derived adminHost/adminPort/tlsServerName/metricsPort fields added."""
    doc = load_deployments_document(repo_root)
    for key in ("environment", "runtimeNamespace", "monitoringNamespace", "dnsDomain", "deployments"):
        if key not in doc:
            raise ConfigError(f"goldengate-deployments.yaml: missing required key {key!r}")

    entries = doc["deployments"]
    if not isinstance(entries, list) or not entries:
        raise ConfigError("goldengate-deployments.yaml: 'deployments' must be a non-empty list")

    runtime_namespace = doc["runtimeNamespace"]
    dns_domain = doc["dnsDomain"]

    seen = set()
    deployments = []
    for entry in entries:
        for field in ("name", "type", "pipeline", "role"):
            if not entry.get(field):
                raise ConfigError(f"deployment entry missing required field {field!r}: {entry!r}")
        name = entry["name"]
        if name in seen:
            raise ConfigError(f"duplicate deployment name {name!r}")
        seen.add(name)
        if entry["role"] not in ("source", "target"):
            raise ConfigError(f"{name}: role must be 'source' or 'target', got {entry['role']!r}")

        # ingressEnabled is a REQUIRED, literal Boolean field of the generated registry (hack/goldengate-deployment-model.py's build_registry() always sets it) -- no truthy/falsy coercion of a string/int/null is ever accepted, so a malformed value such as "false" (a truthy Python string) can never be silently treated as enabled.
        raw_ingress_enabled = entry.get("ingressEnabled")
        if not _is_literal_bool(raw_ingress_enabled):
            raise ConfigError(f"{name}: ingressEnabled must be a literal Boolean, got {raw_ingress_enabled!r}")
        ingress_enabled = raw_ingress_enabled

        # ingressHost is likewise REQUIRED and must already be a validly-shaped hostname -- the registry's own canonically-resolved value (see hack/goldengate-deployment-model.py's runtimeIngressHost), never reconstructed here from name+dnsDomain. Malformed canonical topology fails the whole config load closed rather than silently producing no link for one runtime.
        raw_ingress_host = entry.get("ingressHost")
        if not _is_valid_ingress_host(raw_ingress_host):
            raise ConfigError(f"{name}: ingressHost must be a valid hostname, got {raw_ingress_host!r}")
        ingress_host = raw_ingress_host

        deployments.append({
            "name": name,
            "type": entry["type"],
            "pipeline": entry["pipeline"],
            "role": entry["role"],
            "enabled": bool(entry.get("enabled", False)),
            "adminSecret": entry.get("adminSecret", ""),
            "adminHost": _admin_host(name, runtime_namespace),
            "adminPort": int(entry.get("adminPort", DEFAULT_ADMIN_PORT)),
            "tlsServerName": _tls_server_name(name, dns_domain),
            "metricsPort": int(entry.get("metricsPort", DEFAULT_METRICS_PORT)),
            "ingressEnabled": ingress_enabled,
            "ingressHost": ingress_host,
            # "Open GoldenGate UI" portal link -- None (never a fabricated URL) whenever the runtime's own Ingress is disabled; ingressHost itself is already validated above regardless of ingressEnabled.
            "consoleUrl": _console_url(ingress_host) if ingress_enabled else None,
        })

    return {
        "environment": doc["environment"],
        "runtimeNamespace": runtime_namespace,
        "monitoringNamespace": doc["monitoringNamespace"],
        "dnsDomain": dns_domain,
        "tlsSecret": doc.get("tlsSecret", ""),
        "deployments": deployments,
    }


class StartupValidationError(Exception):
    def __init__(self, problems):
        self.problems = list(problems)
        super().__init__("; ".join(self.problems))


def validate_enabled_deployments(deployments):
    """Fails startup for any enabled deployment missing a supported type or adminSecret."""
    problems = []
    for d in deployments:
        if not d["enabled"]:
            continue
        if not is_safe_deployment_type(d["type"]):
            problems.append(f"{d['name']}: unsafe deployment type {d['type']!r}")
        if not d["adminSecret"]:
            problems.append(f"{d['name']}: adminSecret is required")
    if problems:
        raise StartupValidationError(problems)


def build_logical_pipelines(deployments):
    """Groups canonical deployments by pipeline -> {role: name}."""
    by_pipeline = {}
    for d in deployments:
        roles = by_pipeline.setdefault(d["pipeline"], {})
        if d["role"] in roles and roles[d["role"]] != d["name"]:
            raise ConfigError(f"pipeline {d['pipeline']!r} has conflicting {d['role']} roles")
        roles[d["role"]] = d["name"]
    return [{"pipelineId": pid, "roles": roles} for pid, roles in sorted(by_pipeline.items())]


def now_epoch():
    return int(time.time())
