sg-008230e74585a543c
gg-poc-dev-node

Then open Inbound rules.

Look specifically for any rule where Source is:

sg-0c7e8e3a14efdf3e3

That sg-0c7... is the controller's shared backend SG we identified from the k8s-traffic-ggpocdev-... name. AWS LBC documents exactly that autogenerated naming pattern and uses this SG as the source in target/node SG rules.

If you find one or more rules referencing:

sg-0c7e8e3a14efdf3e3