apiVersion: v1
kind: Service
metadata:
  name: gg-monitor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "goldengate-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "goldengate-monitor.selectorLabels" . | nindent 4 }}
