{{- if and .Values.ecrTokenSync .Values.ecrTokenSync.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ecrTokenSync.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-ecr-token-sync
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.ecrTokenSync.roleArn }}
{{- end }}
